import { ProjectRepository } from '../../infrastructure/repositories/ProjectRepository';
import { ConfigRepository } from '../../infrastructure/repositories/ConfigRepository';
import { TranslationService } from '../../infrastructure/services/TranslationService';
import { ProjectService } from '../../application/services/ProjectService';
import { ConfigService } from '../../application/services/ConfigService';
const projectRepository = new ProjectRepository();
const configRepository = new ConfigRepository();
const translationService = new TranslationService();
export const projectService = new ProjectService(projectRepository);
export const configService = new ConfigService(configRepository);
export const translations = translationService;
export { projectRepository, configRepository, translationService };
